name: Save PR Diff

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  save-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get code diff
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git diff origin/${{ github.event.pull_request.base.ref }} > code_diff.txt

      - name: Display diff
        run: cat code_diff.txt

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
              python -m pip install --upgrade pip
              pip install requests

      - name: Analyze code with GPT
        run: python getComment.py
      - name: Post Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const commentBody = fs.readFileSync('gpt_response.txt', 'utf8');
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: commentBody
            });