name: Save PR Diff

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  save-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get code diff
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git diff origin/${{ github.event.pull_request.base.ref }} > code_diff.txt

      - name: Display diff
        run: cat code_diff.txt

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
              python -m pip install --upgrade pip
              pip install requests

      - name: Analyze code with GPT
        run: python getComment.py
        env:
          GPT_ENDPOINT: ${{ secrets.GPT_ENDPOINT }}
          GPT_TOKEN: ${{ secrets.GPT_TOKEN }}